-- Generated by Ryoku Settings (ryoku-hub). Do not edit by hand; it is
-- overwritten on every change. Loaded by hyprland.lua after the base modules and
-- before user.lua, so these tweaks override the shipped defaults while your own
-- user.lua still wins. Manage these in Ryoku Settings (Super + ,).

-- hl.config({
--   general = { gaps_in = 10, gaps_out = 28 },
--   decoration = { rounding = 16, active_opacity = 0.96, inactive_opacity = 0.88, blur = { size = 8, passes = 3 }, shadow = { range = 30 } },
--   input = { kb_layout = "us", kb_variant = "", kb_options = "", touchpad = { natural_scroll = true } },
-- })


-- hl.on("hyprland.start", function()
--   hl.exec_cmd("hyprctl setcursor WhiteSur-cursors 24")
-- end)
